spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:example
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # 애플리케이션 로딩시 Drop -> Create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  root: info
  org.hibernate: debug
  org.springframework.web: debug
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  com.jpa.study: debug
# org.hibernate.type: trace